// <auto-generated />
using System;
using DotNetCoreApi_CodeHubGreece;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreApi_CodeHubGreece.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.Country", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.Customer", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("CountryId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.Installation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("CustomerId");

                    b.Property<DateTime>("RefDate");

                    b.Property<ulong>("VersionId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VersionId");

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.InstallationNote", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<ulong>("InstallationId");

                    b.Property<string>("Name");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("UserId");

                    b.ToTable("InstallationNotes");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.Product", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.Version", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<ulong>("ProductId");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("VersionNumber");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.VersionNote", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<ulong>("UserId");

                    b.Property<ulong>("VersionId");

                    b.Property<ulong>("VersionNoteTypeId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VersionId");

                    b.HasIndex("VersionNoteTypeId");

                    b.ToTable("VersionNotes");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.VersionNoteType", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VersionNoteTypes");
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.Customer", b =>
                {
                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.Installation", b =>
                {
                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.Version", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.InstallationNote", b =>
                {
                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.Version", b =>
                {
                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DotNetCoreApi_CodeHubGreece.Models.VersionNote", b =>
                {
                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.Version", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotNetCoreApi_CodeHubGreece.Models.VersionNoteType", "VersionNoteType")
                        .WithMany()
                        .HasForeignKey("VersionNoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
